export const ENROLL_ONLINE_CLASS = "ENROLL_ONLINE_CLASS";
export const SET_PERIOD_ONLINE_CLASS = "SET_PERIOD_ONLINE_CLASS";
export const DISENROLL_ONLINE_CLASS = "DISENROLL_ONLINE_CLASS";
export const SYNC_USER_ONLINE_CLASSES_REQUESTS =
  "SYNC_USER_ONLINE_CLASSES_REQUESTS";
