export const CoachesData = [
  {
    photo: "./images/coaches/coach1.png",
    name: "coach 1",
    info1: "کارشناس علوم ورزش و تربیت بدنی",
    info2: "کارشناس علوم ورزش و تربیت بدنی",
    info3: "کارشناس علوم ورزش و تربیت بدنی",
    info4: "کارشناس علوم ورزش و تربیت بدنی",
    resume: "12",
    attendance_classes: "some classs",
    online_classes: "some classes",
    instagram_link: "instagram.com",
    twitter_link: "twitter.com",
    facebook_link: "facebook.com",
    id: 1,
  },
  {
    photo: "./images/coaches/coach2.png",
    name: "coach 2",
    info1: "کارشناس علوم ورزش و تربیت بدنی",
    info2: "کارشناس علوم ورزش و تربیت بدنی",
    info3: "کارشناس علوم ورزش و تربیت بدنی",
    info4: "کارشناس علوم ورزش و تربیت بدنی",
    resume: "12",
    attendance_classes: "some classs",
    online_classes: "some classes",
    instagram_link: "instagram.com",
    twitter_link: "twitter.com",
    facebook_link: "facebook.com",
    id: 2,
  },
  {
    photo: "./images/coaches/coach3.png",
    name: "coach 3",
    info1: "کارشناس علوم ورزش و تربیت بدنی",
    info2: "کارشناس علوم ورزش و تربیت بدنی",
    info3: "کارشناس علوم ورزش و تربیت بدنی",
    info4: "کارشناس علوم ورزش و تربیت بدنی",
    resume: "12",
    attendance_classes: "some classs",
    online_classes: "some classes",
    instagram_link: "instagram.com",
    twitter_link: "twitter.com",
    facebook_link: "facebook.com",
    id: 3,
  },
  {
    photo: "./images/coaches/coach4.png",
    name: "coach 4",
    info1: "کارشناس علوم ورزش و تربیت بدنی",
    info2: "کارشناس علوم ورزش و تربیت بدنی",
    info3: "کارشناس علوم ورزش و تربیت بدنی",
    info4: "کارشناس علوم ورزش و تربیت بدنی",
    resume: "12",
    attendance_classes: "some classs",
    online_classes: "some classes",
    instagram_link: "instagram.com",
    twitter_link: "twitter.com",
    facebook_link: "facebook.com",
    id: 4,
  },
  {
    photo: "./images/coaches/coach5.png",
    name: "coach 5",
    info1: "کارشناس علوم ورزش و تربیت بدنی",
    info2: "کارشناس علوم ورزش و تربیت بدنی",
    info3: "کارشناس علوم ورزش و تربیت بدنی",
    info4: "کارشناس علوم ورزش و تربیت بدنی",
    resume: "12",
    attendance_classes: "some classs",
    online_classes: "some classes",
    instagram_link: "instagram.com",
    twitter_link: "twitter.com",
    facebook_link: "facebook.com",
    id: 5,
  },
  {
    photo: "./images/coaches/coach6.png",
    name: "coach 6",
    info1: "کارشناس علوم ورزش و تربیت بدنی",
    info2: "کارشناس علوم ورزش و تربیت بدنی",
    info3: "کارشناس علوم ورزش و تربیت بدنی",
    info4: "کارشناس علوم ورزش و تربیت بدنی",
    resume: "12",
    attendance_classes: "some classs",
    online_classes: "some classes",
    instagram_link: "instagram.com",
    twitter_link: "twitter.com",
    facebook_link: "facebook.com",
    id: 6,
  },
];
