export const RENEWAL_ATTENDING_CLASS_SUCCESS =
  "RENEWAL_ATTENDING_CLASS_SUCCESS";
export const RENEWAL_ATTENDING_CLASS_FAIL = "RENEWAL_ATTENDING_CLASS_FAIL";

export const RENEWAL_ONLINE_CLASS_SUCCESS = "RENEWAL_ONLINE_CLASS_SUCCESS";
export const RENEWAL_ONLINE_CLASS_FAIL = "RENEWAL_ONLINE_CLASS_FAIL";
