# Generated by Django 3.2.6 on 2022-05-11 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('telephone', models.IntegerField()),
                ('instagram_link', models.URLField()),
                ('facebook_link', models.URLField()),
                ('twitter_link', models.URLField()),
            ],
        ),
    ]
