export const GET_ENROLLED_ATTENDING_CLASSES = "GET_ENROLLED_ATTENDING_CLASSES";
export const GET_ENROLLED_ONLINE_CLASSES = "GET_ENROLLED_ONLINE_CLASSES";
export const GET_ENROLLED_ATTENDING_CLASSES_FAIL =
  "GET_ENROLLED_ATTENDING_CLASSES_FAIL";
export const GET_ENROLLED_ONLINE_CLASSES_FAIL =
  "GET_ENROLLED_ONLINE_CLASSES_FAIL";

export const RESET_ENROLLED_CLASSES = "RESET_ENROLLED_CLASSES";
