export const USER_DETAILS_UPDATE_REQUEST = "USER_DETAILS_UPDATE_REQUEST";
export const USER_DETAILS_UPDATE_REQUEST_SUCCESS =
  "USER_DETAILS_UPDATE_REQUEST_SUCCESS";
export const USER_DETAILS_UPDATE_REQUEST_FAIL =
  "USER_DETAILS_UPDATE_REQUEST_FAIL";
