# Generated by Django 4.0.4 on 2022-06-14 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enrolment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendingclassesenrolled',
            name='left_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendingclassesenrolled',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='attendingclassesenrolled',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='onlineclassesenrolled',
            name='left_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='onlineclassesenrolled',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='onlineclassesenrolled',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='BaseClassesEnrolled',
        ),
    ]
