export const ENROLL_ATTENDING_CLASS = "ENROLL_ATTENDING_CLASS";
export const SET_PERIOD_ATTENDING_CLASS = "SET_PERIOD_ATTENDING_CLASS";
export const DISENROLL_ATTENDING_CLASS = "DISENROLL_ATTENDING_CLASS";
export const SYNC_USER_REQUESTS = "SYNC_USER_REQUESTS";
