# Generated by Django 3.2.6 on 2022-05-11 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('monthly_fee', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('شنبه', 'شنبه'), ('یکشنبه', 'یکشنبه'), ('دوشنبه', 'دوشنبه'), ('سه شنبه', 'سه شنبه'), ('چهارشنبه', 'چهارشنبه'), ('پنجشنبه', 'پنجشنبه'), ('جمعه', 'جمعه')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='AttendingClass',
            fields=[
                ('baseclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='classes.baseclass')),
                ('image', models.ImageField(upload_to='classes/attending_classes/%Y/%m/%d')),
            ],
            bases=('classes.baseclass',),
        ),
        migrations.CreateModel(
            name='OnlineClass',
            fields=[
                ('baseclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='classes.baseclass')),
                ('image', models.ImageField(upload_to='classes/private_online_classes/%Y/%m/%d')),
                ('is_public', models.BooleanField(default=False)),
            ],
            bases=('classes.baseclass',),
        ),
    ]
