# Generated by Django 3.2.6 on 2022-05-11 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coaches', '0001_initial'),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseclass',
            name='coach',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coaches.coach'),
        ),
        migrations.AddField(
            model_name='baseclass',
            name='schedule',
            field=models.ManyToManyField(to='classes.Schedule'),
        ),
    ]
