# Generated by Django 3.2.6 on 2022-05-11 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='coaches/%Y/%m/%d')),
                ('info_1', models.CharField(blank=True, max_length=200)),
                ('info_2', models.CharField(blank=True, max_length=200)),
                ('info_3', models.CharField(blank=True, max_length=200)),
                ('info_4', models.CharField(blank=True, max_length=200)),
                ('hire_date', models.DateField(auto_now_add=True)),
                ('instagram_link', models.URLField(blank=True)),
                ('facebook_link', models.URLField(blank=True)),
                ('twitter_link', models.URLField(blank=True)),
                ('attending_classes', models.ManyToManyField(blank=True, null=True, related_name='attending_class', to='classes.AttendingClass')),
                ('online_classes', models.ManyToManyField(blank=True, null=True, related_name='online_class', to='classes.OnlineClass')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
